/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.estudo.projetoVendas.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author thaisreis
 */
public class Frmmenu extends javax.swing.JFrame {

    public String usuariologado;
    
    
    /**
     * Creates new form Frmmenu
     */
    public Frmmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        JPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cliente = new javax.swing.JMenu();
        clientes_controle = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        funcionarios_controle = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        fornecedores_controle = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        produtos_estoque = new javax.swing.JMenuItem();
        produtos_consulta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        vendas_pdv = new javax.swing.JMenuItem();
        vendas_posicao = new javax.swing.JMenuItem();
        vendas_historico = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        config_trocar_usuario = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Estoque");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel1.setText("Usuário logado:");

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(0, 0, 255));
        lblusuario.setText("Thais Reis");

        javax.swing.GroupLayout JPanel3Layout = new javax.swing.GroupLayout(JPanel3);
        JPanel3.setLayout(JPanel3Layout);
        JPanel3Layout.setHorizontalGroup(
            JPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblusuario)
                .addContainerGap(800, Short.MAX_VALUE))
        );
        JPanel3Layout.setVerticalGroup(
            JPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblusuario))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(JPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 344, Short.MAX_VALUE)
                .addComponent(JPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cliente.setIcon(new javax.swing.ImageIcon("/Users/thaisreis/Documents/java/projetoVendas/src/main/java/imagens/clientes.png")); // NOI18N
        cliente.setText("Clientes");

        clientes_controle.setText("Controle de Clientes");
        clientes_controle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientes_controleActionPerformed(evt);
            }
        });
        cliente.add(clientes_controle);

        jMenuBar1.add(cliente);

        jMenu2.setIcon(new javax.swing.ImageIcon("/Users/thaisreis/Documents/java/projetoVendas/src/main/java/imagens/funcionarios.png")); // NOI18N
        jMenu2.setText("Funcionários");

        funcionarios_controle.setText("Controle de Funcionários");
        funcionarios_controle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarios_controleActionPerformed(evt);
            }
        });
        jMenu2.add(funcionarios_controle);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon("/Users/thaisreis/Documents/java/projetoVendas/src/main/java/imagens/fornecedores.png")); // NOI18N
        jMenu3.setText("Fornecedores");

        fornecedores_controle.setText("Controle de Fornecedores");
        fornecedores_controle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedores_controleActionPerformed(evt);
            }
        });
        jMenu3.add(fornecedores_controle);

        jMenuBar1.add(jMenu3);

        jMenu6.setIcon(new javax.swing.ImageIcon("/Users/thaisreis/Documents/java/projetoVendas/src/main/java/imagens/produtos.png")); // NOI18N
        jMenu6.setText("Produtos");

        produtos_estoque.setText("Controle de Estoque");
        produtos_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtos_estoqueActionPerformed(evt);
            }
        });
        jMenu6.add(produtos_estoque);

        produtos_consulta.setText("Consulta de Produtos");
        produtos_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtos_consultaActionPerformed(evt);
            }
        });
        jMenu6.add(produtos_consulta);

        jMenuBar1.add(jMenu6);

        jMenu4.setIcon(new javax.swing.ImageIcon("/Users/thaisreis/Documents/java/projetoVendas/src/main/java/imagens/vendas.png")); // NOI18N
        jMenu4.setText("Vendas");

        vendas_pdv.setText("Abrir PDV");
        vendas_pdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendas_pdvActionPerformed(evt);
            }
        });
        jMenu4.add(vendas_pdv);

        vendas_posicao.setText("Posição do Dia");
        vendas_posicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendas_posicaoActionPerformed(evt);
            }
        });
        jMenu4.add(vendas_posicao);

        vendas_historico.setText("Histórico de Vendas");
        vendas_historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendas_historicoActionPerformed(evt);
            }
        });
        jMenu4.add(vendas_historico);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon("/Users/thaisreis/Documents/java/projetoVendas/src/main/java/imagens/configuracoes.png")); // NOI18N
        jMenu5.setText("Configurações");

        config_trocar_usuario.setText("Trocar de Usuário");
        config_trocar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                config_trocar_usuarioMouseClicked(evt);
            }
        });
        config_trocar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                config_trocar_usuarioActionPerformed(evt);
            }
        });
        jMenu5.add(config_trocar_usuario);

        jMenuBar1.add(jMenu5);

        sair.setIcon(new javax.swing.ImageIcon("/Users/thaisreis/Documents/java/projetoVendas/src/main/java/imagens/sair.png")); // NOI18N
        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcionarios_controleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarios_controleActionPerformed
        // Abre a tela de controle de funcionarios
        FrmFuncionarios tela = new FrmFuncionarios();
        tela.setVisible(true);
        
    }//GEN-LAST:event_funcionarios_controleActionPerformed

    private void produtos_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtos_consultaActionPerformed
        // Abrir tela de consulta de produtos
        FrmProdutos tela = new FrmProdutos();
        tela.jTabbedPane1.setSelectedIndex(1);
        tela.setVisible(true);
    }//GEN-LAST:event_produtos_consultaActionPerformed

    private void vendas_pdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendas_pdvActionPerformed
        // Abre a tela de consulta de pontos de venda
        FrmVendas tela = new FrmVendas();
        tela.setVisible(true);
    }//GEN-LAST:event_vendas_pdvActionPerformed

    private void vendas_posicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendas_posicaoActionPerformed
        // Abre a tela de total de vendas por dia/data
        FrmTotalVenda tela = new FrmTotalVenda();
        tela.setVisible(true);
    }//GEN-LAST:event_vendas_posicaoActionPerformed

    private void produtos_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtos_estoqueActionPerformed
        // Abre a tela de consulta de estoque de produtos
        FrmEstoque tela = new FrmEstoque();
        tela.setVisible(true);
    }//GEN-LAST:event_produtos_estoqueActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //Deixar o menu ocupando toda a tela
        this.setExtendedState(this.MAXIMIZED_BOTH);
        lblusuario.setText(usuariologado);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void vendas_historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendas_historicoActionPerformed
        // Abre tela de historico de vendas
        FrmHistorico tela = new FrmHistorico();
        tela.setVisible(true);
    }//GEN-LAST:event_vendas_historicoActionPerformed

    private void config_trocar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_config_trocar_usuarioActionPerformed
        // Fazer logout
        FrmLogin telalogin = new FrmLogin();
        this.dispose();
        telalogin.setVisible(true);
    }//GEN-LAST:event_config_trocar_usuarioActionPerformed

    private void config_trocar_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_config_trocar_usuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_config_trocar_usuarioMouseClicked

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // Botao sair
        int op;
        op = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja sair?");
        
        if (op == 0) {
        System.exit(0);
        }
    }//GEN-LAST:event_sairMouseClicked

    private void clientes_controleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientes_controleActionPerformed
        // Abre tela de controle de cliente 
        Frmcliente tela = new Frmcliente();
        tela.setVisible(true);
    }//GEN-LAST:event_clientes_controleActionPerformed

    private void fornecedores_controleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedores_controleActionPerformed
        // Abre a tela de controle de fornecedores
        FrmFornecedores tela = new FrmFornecedores();
        tela.setVisible(true);
    }//GEN-LAST:event_fornecedores_controleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel3;
    private javax.swing.JMenu cliente;
    private javax.swing.JMenuItem clientes_controle;
    private javax.swing.JMenuItem config_trocar_usuario;
    private javax.swing.JMenuItem fornecedores_controle;
    private javax.swing.JMenuItem funcionarios_controle;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JMenuItem produtos_consulta;
    private javax.swing.JMenuItem produtos_estoque;
    private javax.swing.JMenu sair;
    public javax.swing.JMenuItem vendas_historico;
    private javax.swing.JMenuItem vendas_pdv;
    public javax.swing.JMenuItem vendas_posicao;
    // End of variables declaration//GEN-END:variables
}
